/**
 * Auto-generated member seed data from Google Sheets export.
 * Generated on: 2026-02-12T01:23:01.104Z
 *
 * When a member signs up for the first time, we look up their email here
 * and auto-populate their profile with the data from the spreadsheet.
 *
 * DO NOT EDIT MANUALLY — regenerate with:
 *   node scripts/generate-seed-data.mjs
 */

export interface MemberSeedProfile {
  full_name?: string;
  gender?: string;
  whatsapp_number?: string;
  birthday?: string;
  primary_track?: string;
  secondary_track?: string;
  student_status?: string;
  matric_no?: string;
  department?: string;
  faculty?: string;
  primary_skill_level?: string;
}

/** Lookup by lowercase email → pre-filled profile fields */
export const MEMBER_SEED_DATA: Record<string, MemberSeedProfile> = {
  "favour870487@gmail.com": {
    "full_name": "Ajao-Rotimi Favour Inioluwa",
    "gender": "Female",
    "whatsapp_number": "+2348122229581",
    "birthday": "2000-11-11",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "22/0024",
    "department": "Software Engineering",
    "faculty": "School of Computing",
    "primary_skill_level": "2"
  },
  "imjustcruzzin@gmail.com": {
    "full_name": "Sijuade Cruz Yinka-Mafe",
    "gender": "Male",
    "whatsapp_number": "+2347044251887",
    "birthday": "2000-08-26",
    "primary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "23/0036",
    "department": "Software Engineering",
    "faculty": "School of Computing",
    "primary_skill_level": "1"
  },
  "timilehinduroishola@gmail.com": {
    "full_name": "Duro-Ishola Oluwatimilehin Olukayode",
    "gender": "Male",
    "whatsapp_number": "+2347041154193",
    "birthday": "2000-03-09",
    "primary_track": "Infrastructure & Security",
    "student_status": "Current Student",
    "matric_no": "23/0224",
    "department": "Software Engineering",
    "faculty": "School of Computing",
    "primary_skill_level": "2"
  },
  "ugochukwuchinomnso@gmail.com": {
    "full_name": "Ugochukwu Chinomnso Ugochukwu",
    "gender": "Male",
    "whatsapp_number": "+2349068313671",
    "birthday": "2000-11-11",
    "primary_track": "Infrastructure & Security",
    "student_status": "Current Student",
    "matric_no": "24/0678",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "1"
  },
  "nanboldassak2@gmail.com": {
    "full_name": "Nanbol Dassak",
    "gender": "Male",
    "whatsapp_number": "+2347037371590",
    "birthday": "2000-07-03",
    "primary_track": "Data & AI",
    "secondary_track": "Design & Management",
    "student_status": "Current Student",
    "matric_no": "23/0251",
    "department": "Software Engineering",
    "faculty": "School of Computing",
    "primary_skill_level": "3"
  },
  "maroathora@gmail.com": {
    "full_name": "Divine Athora",
    "gender": "Male",
    "whatsapp_number": "+2348153148154",
    "birthday": "2000-02-23",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Design & Management",
    "student_status": "Current Student",
    "matric_no": "23/0133",
    "department": "Software Engineering",
    "faculty": "School of Computing",
    "primary_skill_level": "3"
  },
  "tokkyayoajayi@gmail.com": {
    "full_name": "Oluwatokiloba Ayo-Ajayi",
    "gender": "Female",
    "whatsapp_number": "+2347036462900",
    "birthday": "2000-11-28",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Infrastructure & Security",
    "student_status": "Current Student",
    "matric_no": "23/0069",
    "department": "Software Engineering",
    "faculty": "School of Computing",
    "primary_skill_level": "2"
  },
  "yadahdaniels@gmail.com": {
    "full_name": "Daniels Praise ifechukwu",
    "gender": "Female",
    "whatsapp_number": "+2348083348981",
    "birthday": "2000-07-14",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "23/0278",
    "department": "Software Engineering",
    "faculty": "School of Computing",
    "primary_skill_level": "3"
  },
  "orevian28@gmail.com": {
    "full_name": "Oreoluwa Vivian Ogunjemiyo",
    "gender": "Female",
    "whatsapp_number": "+2347073859324",
    "birthday": "2000-10-28",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Design & Management",
    "student_status": "Current Student",
    "matric_no": "24/0022",
    "department": "Software Engineering",
    "faculty": "School of Computing",
    "primary_skill_level": "2"
  },
  "okaforaudrey@gmail.com": {
    "full_name": "Ifeatu Audrey Okafor",
    "gender": "Female",
    "whatsapp_number": "+2348143162929",
    "birthday": "2000-03-18",
    "primary_track": "Data & AI",
    "secondary_track": "Infrastructure & Security",
    "student_status": "Current Student",
    "matric_no": "24/0736",
    "department": "Information Technology",
    "faculty": "School of Computing",
    "primary_skill_level": "1"
  },
  "bshina831@gmail.com": {
    "full_name": "BABALOLA OLUWASHINAAYOMI DANIEL",
    "gender": "Male",
    "whatsapp_number": "+2349069063098",
    "birthday": "2000-07-15",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "23/0111",
    "department": "Software Engineering",
    "faculty": "School of Computing",
    "primary_skill_level": "2"
  },
  "dubemosigwe@gmail.com": {
    "full_name": "Chidubem",
    "gender": "Male",
    "whatsapp_number": "+2348147365382",
    "birthday": "2000-12-06",
    "primary_track": "Data & AI",
    "secondary_track": "Infrastructure & Security",
    "student_status": "Current Student",
    "matric_no": "241494",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "1"
  },
  "sophiaduruike@gmail.com": {
    "full_name": "Duruike Sophia Ijeure",
    "gender": "Female",
    "whatsapp_number": "+2349137162926",
    "birthday": "2000-12-12",
    "primary_track": "Design & Management",
    "student_status": "Current Student",
    "matric_no": "24/0258",
    "department": "Software Engineering",
    "faculty": "School of Computing",
    "primary_skill_level": "1"
  },
  "davidfatunmbi1@gmail.com": {
    "full_name": "David Afolabi Fatunmbi",
    "gender": "Male",
    "whatsapp_number": "+2349060449009",
    "birthday": "2000-05-16",
    "primary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "24/0043",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "1"
  },
  "ononookon216@gmail.com": {
    "full_name": "Onono Okon",
    "gender": "Female",
    "whatsapp_number": "+2347043030383",
    "birthday": "2000-07-26",
    "primary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "22/1194",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "2"
  },
  "nnavicchidiebube@gmail.com": {
    "full_name": "Victor Chidiebube Onuigbo",
    "gender": "Male",
    "whatsapp_number": "+2349137368075",
    "birthday": "2000-04-07",
    "primary_track": "Infrastructure & Security",
    "student_status": "Current Student",
    "matric_no": "24/0484",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "1"
  },
  "eyomaakanimo@gmail.com": {
    "full_name": "Akanimo Eyoma",
    "gender": "Male",
    "whatsapp_number": "+2348139534440",
    "birthday": "2000-12-30",
    "primary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "22/2974",
    "department": "Information Technology",
    "faculty": "School of Computing",
    "primary_skill_level": "3"
  },
  "atejioyebolu@gmail.com": {
    "full_name": "Atejioye Anuoluwapo",
    "gender": "Male",
    "whatsapp_number": "+2349135629916",
    "birthday": "2000-10-26",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Infrastructure & Security",
    "student_status": "Current Student",
    "matric_no": "24/1702",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "1"
  },
  "wisdomchikwendu2005@gmail.com": {
    "full_name": "Wisdom Chidera Chikwendu",
    "gender": "Male",
    "whatsapp_number": "+2348060670647",
    "birthday": "2000-05-22",
    "primary_track": "Software Development & Engineering",
    "student_status": "Current Student",
    "matric_no": "23/0244",
    "department": "Software Engineering",
    "faculty": "School of Computing",
    "primary_skill_level": "3"
  },
  "onuohai1700@student.babcock.edu.ng": {
    "full_name": "Onuoha Ikechukwu David",
    "gender": "Male",
    "whatsapp_number": "+2349035997559",
    "primary_track": "Software Development & Engineering",
    "student_status": "Current Student",
    "matric_no": "24/2354",
    "department": "Software Engineering",
    "faculty": "School of Computing",
    "primary_skill_level": "2"
  },
  "godsentasotie@gmail.com": {
    "full_name": "Godsent Asotie",
    "gender": "Male",
    "whatsapp_number": "+2349076706267",
    "birthday": "2000-09-27",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "23/0048",
    "department": "Software Engineering",
    "faculty": "School of Computing",
    "primary_skill_level": "3"
  },
  "beniola589@gmail.com": {
    "full_name": "Eniola Balogun",
    "gender": "Female",
    "whatsapp_number": "+2348108474435",
    "birthday": "2000-11-04",
    "primary_track": "Software Development & Engineering",
    "student_status": "Current Student",
    "matric_no": "23/0258",
    "department": "Software Engineering",
    "faculty": "School of Computing",
    "primary_skill_level": "3"
  },
  "akinsboms@gmail.com": {
    "full_name": "Boma Akins",
    "gender": "Female",
    "whatsapp_number": "+2349067073238",
    "birthday": "2000-06-12",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "22/2402",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "3"
  },
  "ekekwec5439@student.babcock.edu.ng": {
    "full_name": "Ekekwe Divine Chukwuemeka",
    "gender": "Male",
    "whatsapp_number": "+2348036886377",
    "birthday": "2000-04-20",
    "primary_track": "Software Development & Engineering",
    "student_status": "Current Student",
    "matric_no": "23/0084",
    "department": "Software Engineering",
    "faculty": "School of Computing",
    "primary_skill_level": "4"
  },
  "tomotola88@gmail.com": {
    "full_name": "Towolawi Omotola Faith",
    "gender": "Female",
    "whatsapp_number": "+2348105106896",
    "birthday": "2000-07-05",
    "primary_track": "Infrastructure & Security",
    "student_status": "Current Student",
    "matric_no": "22/1695",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "2"
  },
  "emmanuel-dacod0833@student.babcock.edu.ng": {
    "full_name": "Denzel Emmanuel-Daco",
    "gender": "Male",
    "whatsapp_number": "+2347067053953",
    "birthday": "2000-02-15",
    "primary_track": "Software Development & Engineering",
    "student_status": "Current Student",
    "matric_no": "23/0247",
    "department": "Software Engineering",
    "faculty": "School of Computing",
    "primary_skill_level": "3"
  },
  "chidubems1277@student.babcock.edu.ng": {
    "full_name": "Sarah Chidubem",
    "gender": "Female",
    "whatsapp_number": "+2347089347172",
    "birthday": "2000-02-24",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "23/0256",
    "department": "Software Engineering",
    "faculty": "School of Computing",
    "primary_skill_level": "2"
  },
  "kachionuorah2007@gmail.com": {
    "full_name": "Kasaluchi Claire Onuorah",
    "gender": "Female",
    "whatsapp_number": "+2348105868878",
    "birthday": "2000-06-01",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Design & Management",
    "student_status": "Current Student",
    "matric_no": "24/1097",
    "department": "Software Engineering",
    "faculty": "School of Computing",
    "primary_skill_level": "1"
  },
  "atafodavid9@gmail.com": {
    "full_name": "Atafo David",
    "gender": "Male",
    "whatsapp_number": "+2349033881740",
    "birthday": "2000-07-31",
    "primary_track": "Software Development & Engineering",
    "student_status": "Current Student",
    "matric_no": "23/0005",
    "department": "Software Engineering",
    "faculty": "School of Computing",
    "primary_skill_level": "3"
  },
  "tobilobaawoniyi7@gmail.com": {
    "full_name": "Awoniyi Tobiloba Daniel",
    "gender": "Male",
    "whatsapp_number": "+2348030634213",
    "birthday": "2000-05-15",
    "primary_track": "Design & Management",
    "student_status": "Current Student",
    "matric_no": "23/0956",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "3"
  },
  "divineebube67@gmail.com": {
    "full_name": "Divine Chimobi",
    "gender": "Male",
    "whatsapp_number": "+2348149679503",
    "birthday": "2000-01-25",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Design & Management",
    "student_status": "Current Student",
    "matric_no": "23/0092",
    "department": "Software Engineering",
    "faculty": "School of Computing",
    "primary_skill_level": "2"
  },
  "emana31106@gmail.com": {
    "full_name": "Osuwake Edet Emana",
    "gender": "Male",
    "whatsapp_number": "+2347042154341",
    "birthday": "2000-11-03",
    "primary_track": "Software Development & Engineering",
    "student_status": "Current Student",
    "matric_no": "23/0057",
    "department": "Software Engineering",
    "faculty": "School of Computing",
    "primary_skill_level": "2"
  },
  "arolem0512@student.babcock.edu.ng": {
    "full_name": "Mubaraq",
    "gender": "Male",
    "whatsapp_number": "+2348144783713",
    "birthday": "2000-04-30",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "23/0236",
    "department": "Software Engineering",
    "faculty": "School of Science And Technology",
    "primary_skill_level": "3"
  },
  "fatunmbid0061@student.babcock.edu.ng": {
    "full_name": "David Afolabi Fatunmbi",
    "gender": "Male",
    "whatsapp_number": "+2349060449009",
    "birthday": "2000-05-16",
    "primary_track": "Infrastructure & Security",
    "student_status": "Current Student",
    "matric_no": "24/0043",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "1"
  },
  "ajibolafolahan@gmail.com": {
    "full_name": "Ajibola Folahan Abiola",
    "gender": "Male",
    "whatsapp_number": "+2349076558605",
    "birthday": "2000-07-13",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "22/0831",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "3"
  },
  "ogunyemioyetola28@gmail.com": {
    "full_name": "Ogunyemi Oyetola",
    "gender": "Male",
    "whatsapp_number": "+2349059128991",
    "birthday": "2000-03-21",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "23/2537",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "2"
  },
  "habeebabayomi6@gmail.com": {
    "full_name": "Habeeb Muhammed",
    "gender": "Male",
    "whatsapp_number": "+2349039287440",
    "birthday": "2000-06-30",
    "primary_track": "Infrastructure & Security",
    "secondary_track": "Design & Management",
    "student_status": "Current Student",
    "matric_no": "23/2970",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "3"
  },
  "jeffreyemelike13@gmail.com": {
    "full_name": "Jeffrey Emelike",
    "gender": "Male",
    "whatsapp_number": "+2348136348110",
    "birthday": "2000-07-05",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "23/0195",
    "department": "Software Engineering",
    "faculty": "School of Computing",
    "primary_skill_level": "3"
  },
  "davechuks06@gmail.com": {
    "full_name": "Chuka Ogbonna",
    "gender": "Male",
    "whatsapp_number": "+2347061470305",
    "birthday": "2000-08-27",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Infrastructure & Security",
    "student_status": "Current Student",
    "matric_no": "24/1016",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "1"
  },
  "leinadaniel06@gmail.com": {
    "full_name": "Ajibola Daniel Oluwadamilola",
    "gender": "Male",
    "whatsapp_number": "+2347037238466",
    "birthday": "2000-06-01",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "22/0204",
    "department": "Software Engineering",
    "faculty": "School of Computing",
    "primary_skill_level": "1"
  },
  "murewatajala@gmail.com": {
    "full_name": "Murewa Ajala",
    "gender": "Male",
    "whatsapp_number": "+2349012995866",
    "birthday": "2000-06-20",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "22/2874",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "4"
  },
  "afapeo@gmail.com": {
    "full_name": "Oluwaseyifunmi Esther Afape",
    "gender": "Female",
    "whatsapp_number": "+2347042994795",
    "birthday": "2000-05-28",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "22/1914",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "1"
  },
  "igwezebenjamin84@gmail.com": {
    "full_name": "Igweze Benjamin chidozie",
    "gender": "Male",
    "whatsapp_number": "+2347011229294",
    "birthday": "2000-11-06",
    "primary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "23/1398",
    "department": "Computer Engineering",
    "faculty": "Engineering",
    "primary_skill_level": "1"
  },
  "uchennaakubuiro@gmail.com": {
    "full_name": "Uchenna Akubuiro",
    "gender": "Male",
    "whatsapp_number": "+2348088195953",
    "birthday": "2000-04-10",
    "primary_track": "Software Development & Engineering",
    "student_status": "Current Student",
    "matric_no": "22/0222",
    "department": "Software Engineering",
    "faculty": "School of Computing",
    "primary_skill_level": "3"
  },
  "agunbiadeayomide305@gmail.com": {
    "full_name": "Ayomide Agunbiade",
    "gender": "Male",
    "whatsapp_number": "+2347061651085",
    "birthday": "2000-03-07",
    "primary_track": "Infrastructure & Security",
    "student_status": "Current Student",
    "matric_no": "24/2578",
    "department": "Software Engineering",
    "faculty": "School of Computing",
    "primary_skill_level": "2"
  },
  "o.fatunasee@gmail.com": {
    "full_name": "Olamide Fatunase",
    "gender": "Female",
    "whatsapp_number": "+2348113775001",
    "birthday": "2000-04-20",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Design & Management",
    "student_status": "Current Student",
    "matric_no": "24/1958",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "4"
  },
  "akpotohwoo@gmail.com": {
    "full_name": "Chukwuneku Akpotohwo",
    "gender": "Male",
    "whatsapp_number": "+2348101694302",
    "birthday": "2000-03-29",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Infrastructure & Security",
    "student_status": "Current Student",
    "matric_no": "22/1227",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "3"
  },
  "omobolanle.shaibu@gmail.com": {
    "full_name": "Omobolanle Shaibu",
    "gender": "Female",
    "whatsapp_number": "+2349131118449",
    "birthday": "2000-08-02",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Infrastructure & Security",
    "student_status": "Current Student",
    "matric_no": "23/0389",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "4"
  },
  "adedayofootball@gmail.com": {
    "full_name": "Timilehin ADEDAYO",
    "gender": "Male",
    "whatsapp_number": "+2349067812179",
    "birthday": "2000-05-19",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "22/2130”",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "4"
  },
  "ezekielsimplicity@gmail.com": {
    "full_name": "Keku Ezekiel",
    "gender": "Male",
    "whatsapp_number": "+2349122441049",
    "birthday": "2000-09-05",
    "primary_track": "Data & AI",
    "secondary_track": "Infrastructure & Security",
    "student_status": "Current Student",
    "matric_no": "23/2793",
    "department": "Mechanical Engineering",
    "faculty": "Engineering",
    "primary_skill_level": "1"
  },
  "oluwatamiloreadeniran07@gmail.com": {
    "full_name": "Oluwatamilore Adeniran",
    "gender": "Female",
    "whatsapp_number": "+2348081964417",
    "birthday": "2000-06-19",
    "primary_track": "Data & AI",
    "secondary_track": "Design & Management",
    "student_status": "Current Student",
    "matric_no": "23/0551",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "3"
  },
  "kufreosewilson@gmail.com": {
    "full_name": "Kufre Wilson",
    "gender": "Female",
    "whatsapp_number": "+2349154340014",
    "birthday": "2000-07-25",
    "primary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "24/1500",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "2"
  },
  "odumeruobafunmilola@gmail.com": {
    "full_name": "Mubarak",
    "gender": "Male",
    "whatsapp_number": "+2347010953189",
    "birthday": "2000-03-05",
    "primary_track": "Software Development & Engineering",
    "student_status": "Current Student",
    "matric_no": "23/0122",
    "department": "Software Engineering",
    "faculty": "School of Computing",
    "primary_skill_level": "3"
  },
  "adeizakolamide.ak@gmail.com": {
    "full_name": "Adeiza Fagbamila",
    "gender": "Male",
    "whatsapp_number": "+2349030575493",
    "birthday": "2000-05-31",
    "primary_track": "Infrastructure & Security",
    "secondary_track": "Design & Management",
    "student_status": "Current Student",
    "matric_no": "23/1580",
    "department": "Information Technology",
    "faculty": "School of Computing",
    "primary_skill_level": "1"
  },
  "ayanfe182@gmail.com": {
    "full_name": "Adeogun Ayanfeoluwa Daniel",
    "gender": "Male",
    "whatsapp_number": "+2347048677422",
    "birthday": "2000-10-27",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Infrastructure & Security",
    "student_status": "Current Student",
    "matric_no": "23/0216",
    "department": "Software Engineering",
    "faculty": "School of Computing",
    "primary_skill_level": "2"
  },
  "chukwuemekamarvellous284@gmail.com": {
    "full_name": "Chukwuemeka Solomon",
    "gender": "Male",
    "whatsapp_number": "+2349058505418",
    "birthday": "2000-03-06",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "22/1889",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "1"
  },
  "pwreshy@gmail.com": {
    "full_name": "Atolagbe Precious Olawole",
    "gender": "Male",
    "whatsapp_number": "+2348039887341",
    "birthday": "2000-12-08",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "24/2132",
    "department": "Software Engineering",
    "faculty": "School of Computing",
    "primary_skill_level": "3"
  },
  "moyinoluwa1112a@gmail.com": {
    "full_name": "Moyinoluwa Aina",
    "gender": "Female",
    "whatsapp_number": "+2349161178486",
    "birthday": "2000-02-17",
    "primary_track": "Data & AI",
    "secondary_track": "Infrastructure & Security",
    "student_status": "Current Student",
    "matric_no": "22/0480",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "1"
  },
  "oluwatomilolaarogundade@gmail.com": {
    "full_name": "Oluwatomilola Arogundade",
    "gender": "Female",
    "whatsapp_number": "+2349017334537",
    "birthday": "2000-07-28",
    "primary_track": "Data & AI",
    "secondary_track": "Infrastructure & Security",
    "student_status": "Current Student",
    "matric_no": "22/0908",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "4"
  },
  "olaleyetomisin15@gmail.com": {
    "full_name": "Oluwatomisin Olaleye",
    "gender": "Male",
    "whatsapp_number": "+2349068731444",
    "birthday": "2000-09-29",
    "primary_track": "Design & Management",
    "student_status": "Current Student",
    "matric_no": "23/2813",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "3"
  },
  "niniefut6711@gmail.com": {
    "full_name": "Nini Okon Efut",
    "gender": "Female",
    "whatsapp_number": "+2349060295971",
    "birthday": "2000-08-31",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "24/0997",
    "department": "Software Engineering",
    "faculty": "School of Computing",
    "primary_skill_level": "1"
  },
  "desmondademeso@gmail.com": {
    "full_name": "Ademola Michael Ademeso",
    "gender": "Male",
    "whatsapp_number": "+2348149167007",
    "birthday": "2000-02-04",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "22/2699",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "3"
  },
  "delegundamilare@gmail.com": {
    "full_name": "Abdul Ganiu Damilare Delegun",
    "gender": "Male",
    "whatsapp_number": "+2349054223499",
    "birthday": "2000-03-15",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Design & Management",
    "student_status": "Current Student",
    "matric_no": "22/2214",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "2"
  },
  "ifeomaezeka01@gmail.com": {
    "full_name": "Ifeoma Ezeka",
    "gender": "Female",
    "whatsapp_number": "+2348134152749",
    "birthday": "2000-12-28",
    "primary_track": "Data & AI",
    "secondary_track": "Infrastructure & Security",
    "student_status": "Current Student",
    "matric_no": "22/0137",
    "department": "Software Engineering",
    "faculty": "School of Computing",
    "primary_skill_level": "4"
  },
  "dire1of1@gmail.com": {
    "full_name": "Temidire Ifeanyichukwu Adenuga",
    "gender": "Male",
    "whatsapp_number": "+2349016780658",
    "birthday": "2000-03-30",
    "primary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "22/1482",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "3"
  },
  "ajao0343@pg.babcock.edu.ng": {
    "full_name": "Aisha Ajao",
    "gender": "Female",
    "whatsapp_number": "+2349067659732",
    "birthday": "2000-01-13",
    "primary_track": "Data & AI",
    "secondary_track": "Design & Management",
    "student_status": "Current Student",
    "matric_no": "PG/24/0343",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "2"
  },
  "davidabe600@gmail.com": {
    "full_name": "David Temiloreofejesu Abe",
    "gender": "Male",
    "whatsapp_number": "+2348141116335",
    "birthday": "2000-05-21",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "22/1929",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "3"
  },
  "anjolaoluwa99@gmail.com": {
    "full_name": "Anjolaoluwa Al-Ameen Adeniran",
    "gender": "Male",
    "whatsapp_number": "+2349031915214",
    "birthday": "2000-04-17",
    "primary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "22/0575",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "1"
  },
  "adeboyemoradeyo@gmail.com": {
    "full_name": "Adeboye Moradeyo",
    "gender": "Male",
    "whatsapp_number": "+2348035798866",
    "birthday": "2000-08-13",
    "primary_track": "Infrastructure & Security",
    "student_status": "Current Student",
    "matric_no": "24/0267",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "2"
  },
  "abdulraqibadeniran@gmail.com": {
    "full_name": "Adeniran AbdulRaqib",
    "gender": "Male",
    "whatsapp_number": "+2349154368899",
    "birthday": "2000-08-03",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "22/0578",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "5"
  },
  "kehindeakande067@gmail.com": {
    "full_name": "Kehinde Akande",
    "gender": "Female",
    "whatsapp_number": "+2348081499426",
    "birthday": "2000-02-21",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Design & Management",
    "student_status": "Current Student",
    "matric_no": "22/2175",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "4"
  },
  "adesinacaleb01@gmail.com": {
    "full_name": "Caleb Adesola",
    "gender": "Male",
    "whatsapp_number": "+2349028950689",
    "birthday": "2000-04-25",
    "primary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "1907775554",
    "department": "Biosciences and Biotechnology",
    "faculty": "Engineering",
    "primary_skill_level": "3"
  },
  "dotunkomolafe7@gmail.com": {
    "full_name": "Dotun Komolafe",
    "gender": "Male",
    "whatsapp_number": "+2347073036476",
    "birthday": "2000-07-12",
    "primary_track": "Infrastructure & Security",
    "student_status": "Current Student",
    "matric_no": "24/2606",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "2"
  },
  "enyeobidivinegift@gmail.com": {
    "full_name": "Enyeobi Divinegift",
    "gender": "Male",
    "whatsapp_number": "+2349160663542",
    "birthday": "2000-01-21",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Infrastructure & Security",
    "student_status": "Current Student",
    "matric_no": "23/2374",
    "department": "Computer Engineering",
    "faculty": "Engineering",
    "primary_skill_level": "1"
  },
  "jimmyade577@gmail.com": {
    "full_name": "Adebanjo Olaoluwa John",
    "gender": "Male",
    "whatsapp_number": "+2347014813644",
    "birthday": "2000-08-31",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "22/2534",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "2"
  },
  "kxmisioduleye@gmail.com": {
    "full_name": "Oluwakamisi Oluwasayo Oduleye",
    "gender": "Male",
    "whatsapp_number": "+2348151611610",
    "birthday": "2000-07-12",
    "primary_track": "Data & AI",
    "secondary_track": "Infrastructure & Security",
    "student_status": "Current Student",
    "matric_no": "24/0151",
    "department": "Software Engineering",
    "faculty": "School of Computing",
    "primary_skill_level": "2"
  },
  "omololu150@gmail.com": {
    "full_name": "Olowokure Omololu",
    "gender": "Male",
    "whatsapp_number": "+2347069384087",
    "birthday": "2000-11-26",
    "primary_track": "Data & AI",
    "secondary_track": "Design & Management",
    "student_status": "Current Student",
    "matric_no": "23/2771",
    "department": "Computer Engineering",
    "faculty": "Engineering",
    "primary_skill_level": "2"
  },
  "onuohagianna@gmail.com": {
    "full_name": "Gianna Onuoha",
    "gender": "Female",
    "whatsapp_number": "+2347084954716",
    "birthday": "2000-10-23",
    "primary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "20/0393",
    "department": "Medicine and Surgery",
    "faculty": "Benjamin S. Carson (SENIOR) School of Medicine",
    "primary_skill_level": "1"
  },
  "odiasev6228@student.babcock.edu.ng": {
    "full_name": "Odiase victor osaruese",
    "gender": "Male",
    "whatsapp_number": "+2348115294765",
    "birthday": "2000-09-25",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Design & Management",
    "student_status": "Current Student",
    "matric_no": "23/1305",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "2"
  },
  "imo.cmeka@gmail.com": {
    "full_name": "Chukwuemeka Imo",
    "gender": "Male",
    "whatsapp_number": "+2348065009022",
    "birthday": "2000-09-22",
    "primary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "22/1602",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "1"
  },
  "odelolaprecious@gmail.com": {
    "full_name": "Precious Ayooluwa Odelola",
    "gender": "Female",
    "whatsapp_number": "+2348038802202",
    "birthday": "2000-12-15",
    "primary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "22/2306",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "3"
  },
  "b.olumodan@gmail.com": {
    "full_name": "Boluwaduro Olumodan",
    "gender": "Male",
    "whatsapp_number": "+2347082860989",
    "birthday": "2000-10-28",
    "primary_track": "Design & Management",
    "student_status": "Current Student",
    "matric_no": "24/0708",
    "department": "Economics",
    "faculty": "Babcock Business School",
    "primary_skill_level": "2"
  },
  "kolapokwashie@gmail.com": {
    "full_name": "Michael Kwashie",
    "gender": "Male",
    "whatsapp_number": "+2347012835372",
    "birthday": "2000-08-31",
    "primary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "23/0693",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "1"
  },
  "mikeerap14@gmail.com": {
    "full_name": "Michael Archie Ubong",
    "gender": "Male",
    "whatsapp_number": "+2347016311706",
    "birthday": "2000-11-02",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "22/0044",
    "department": "Software Engineering",
    "faculty": "School of Computing",
    "primary_skill_level": "4"
  },
  "adaezeagwulonu123@gmail.com": {
    "full_name": "AGWULONU ADAEZE STEPHANIE",
    "gender": "Female",
    "whatsapp_number": "+2349040107857",
    "birthday": "2000-11-02",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "24/0979",
    "department": "Software Engineering",
    "faculty": "School of Computing",
    "primary_skill_level": "2"
  },
  "niniefut@gmail.com": {
    "full_name": "Efut Nini Okon",
    "gender": "Female",
    "whatsapp_number": "+2349060295971",
    "birthday": "2000-08-31",
    "primary_track": "Design & Management",
    "student_status": "Current Student",
    "matric_no": "24/0997",
    "department": "Software Engineering",
    "faculty": "School of Computing",
    "primary_skill_level": "1"
  },
  "smileotito123@gmail.com": {
    "full_name": "Okara David Otito",
    "gender": "Male",
    "whatsapp_number": "+2348062997555",
    "birthday": "2000-05-07",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "24/2081",
    "department": "Software Engineering",
    "faculty": "School of Computing",
    "primary_skill_level": "2"
  },
  "geoang222@gmail.com": {
    "full_name": "Tenshi",
    "gender": "Female",
    "whatsapp_number": "+2348035728142",
    "birthday": "2000-11-22",
    "primary_track": "Data & AI",
    "secondary_track": "Infrastructure & Security",
    "student_status": "Non-Student"
  },
  "joshuaakintola7@gmail.com": {
    "full_name": "Joshua",
    "gender": "Male",
    "whatsapp_number": "+2347067571076",
    "birthday": "2000-03-12",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "23/2662",
    "department": "Accounting",
    "faculty": "Management Sciences",
    "primary_skill_level": "3"
  },
  "vincentalvin84@gmail.com": {
    "full_name": "Vincent Alvin",
    "gender": "Male",
    "whatsapp_number": "+2347065630363",
    "birthday": "2000-08-28",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Design & Management",
    "student_status": "Current Student",
    "matric_no": "22/0036",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "2"
  },
  "amaechichibuike697@gmail.com": {
    "full_name": "Amaechi Chibuike Micheal",
    "gender": "Male",
    "whatsapp_number": "+2348168453618",
    "birthday": "2000-08-28",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Infrastructure & Security",
    "student_status": "Current Student",
    "matric_no": "22/0095",
    "department": "Software Engineering",
    "faculty": "School of Computing",
    "primary_skill_level": "3"
  },
  "odusanyaemmanuel810@gmail.com": {
    "full_name": "Odusanya Emmanuel",
    "gender": "Male",
    "whatsapp_number": "+2348087725284",
    "birthday": "2000-12-25",
    "primary_track": "Software Development & Engineering",
    "student_status": "Current Student",
    "matric_no": "24/2053",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "3"
  },
  "alayeroguntobi@gmail.com": {
    "full_name": "Tobiloba Alayerogun",
    "gender": "Male",
    "whatsapp_number": "+2349065757827",
    "birthday": "2000-01-29",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Design & Management",
    "student_status": "Current Student",
    "matric_no": "23/3005",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "2"
  },
  "olowup3356@student.babcock.edu.ng": {
    "full_name": "Olowu Paul",
    "gender": "Male",
    "whatsapp_number": "+2348178015435",
    "birthday": "2000-10-26",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "23/2979",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "2"
  },
  "osesd29@gmail.com": {
    "full_name": "OSEDEBAME EHIGIE ITAMAH",
    "gender": "Male",
    "whatsapp_number": "+2349165914543",
    "birthday": "2000-02-22",
    "primary_track": "Data & AI",
    "secondary_track": "Design & Management",
    "student_status": "Current Student",
    "matric_no": "23/1860",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "3"
  },
  "mobayoomotara3@gmail.com": {
    "full_name": "Mobayo Omotara",
    "gender": "Male",
    "whatsapp_number": "+2348062238185",
    "birthday": "2000-04-22",
    "primary_track": "Data & AI",
    "secondary_track": "Design & Management",
    "student_status": "Current Student",
    "matric_no": "23/1864",
    "department": "Information Technology",
    "faculty": "School of Computing",
    "primary_skill_level": "3"
  },
  "olorundamisi1@gmail.com": {
    "full_name": "Olorundamisi Dunmade",
    "gender": "Male",
    "whatsapp_number": "+2349069725297",
    "birthday": "2000-07-08",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Design & Management",
    "student_status": "Current Student",
    "matric_no": "23/0474",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "5"
  },
  "alukom6149@student.babcock.edu.ng": {
    "full_name": "Olubunmi-Aluko Motunrayo Rehoboth",
    "gender": "Female",
    "whatsapp_number": "+2349059404148",
    "birthday": "2000-04-12",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Infrastructure & Security",
    "student_status": "Current Student",
    "matric_no": "23/0116",
    "department": "Software Engineering",
    "faculty": "School of Computing",
    "primary_skill_level": "2"
  },
  "sophiacyber001@gmail.com": {
    "full_name": "Odiase Sophia Osariemen",
    "gender": "Female",
    "whatsapp_number": "+2349052734169",
    "birthday": "2000-09-26",
    "student_status": "Current Student",
    "matric_no": "23/1268",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "3"
  },
  "nwanonezedavid@gmail.com": {
    "full_name": "NELSON-NWANONEZE DAVID TOCHUKWU",
    "gender": "Male",
    "whatsapp_number": "+2348120327614",
    "birthday": "2000-11-28",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "23/0221",
    "department": "Software Engineering",
    "faculty": "School of Computing",
    "primary_skill_level": "5"
  },
  "nelson-nwanonezes9985@student.babcock.edu.ng": {
    "full_name": "Nelson-Nwanoneze Samuel",
    "gender": "Male",
    "whatsapp_number": "+2349042452497",
    "birthday": "2000-11-28",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "23/0220",
    "department": "Software Engineering",
    "faculty": "School of Computing",
    "primary_skill_level": "3"
  },
  "adedojadaniel@gmail.com": {
    "full_name": "Adedoja Daniel Ademola",
    "gender": "Male",
    "whatsapp_number": "+2348112587999",
    "birthday": "2000-01-03",
    "primary_track": "Design & Management",
    "student_status": "Current Student",
    "matric_no": "22/0008",
    "department": "Software Engineering",
    "faculty": "School of Computing",
    "primary_skill_level": "5"
  },
  "umezinwarita464@gmail.com": {
    "full_name": "UMEZINWA RITA CHISOM",
    "gender": "Female",
    "whatsapp_number": "+2348125600572",
    "birthday": "2000-06-20",
    "primary_track": "Software Development & Engineering",
    "student_status": "Current Student",
    "matric_no": "24/0474",
    "department": "Software Engineering",
    "faculty": "School of Computing",
    "primary_skill_level": "3"
  },
  "alfredogu123@gmail.com": {
    "full_name": "Ogu Alfred",
    "gender": "Male",
    "whatsapp_number": "+2349023094110",
    "birthday": "2000-07-01",
    "primary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "22/1487",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "3"
  },
  "rajifolusho9@gmail.com": {
    "full_name": "Raji Folusho",
    "gender": "Male",
    "whatsapp_number": "+2349011691797",
    "birthday": "2000-10-13",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "23/0290",
    "department": "Software Engineering",
    "faculty": "School of Computing",
    "primary_skill_level": "1"
  },
  "danitunmibi@gmail.com": {
    "full_name": "Daniel Oluwatunmibi",
    "gender": "Male",
    "whatsapp_number": "+2348164303134",
    "birthday": "2000-10-06",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "25/2259",
    "department": "Software Engineering",
    "faculty": "School of Computing",
    "primary_skill_level": "3"
  },
  "adeboyefaousiyat@gmail.com": {
    "full_name": "Adeboye Faouziat Bukanla",
    "gender": "Female",
    "whatsapp_number": "+23408153999168",
    "birthday": "2000-03-15",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "25/0278",
    "department": "Sociology and Social Work",
    "faculty": "Veronica Adeleke School of Social Sciences",
    "primary_skill_level": "1"
  },
  "abisolaoyewole49@gmail.com": {
    "full_name": "Abisola Seyitan Oyewole",
    "gender": "Female",
    "whatsapp_number": "+2348071154284",
    "birthday": "2000-09-20",
    "primary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "22/2046",
    "department": "Computer Science and Information Systems",
    "faculty": "School of Computing",
    "primary_skill_level": "2"
  },
  "lawaljesutomisindeborah@gmail.com": {
    "full_name": "Lawal jesutomisin",
    "gender": "Female",
    "whatsapp_number": "+2348131889145",
    "birthday": "2000-04-12",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Infrastructure & Security",
    "student_status": "Current Student",
    "matric_no": "25/2175",
    "department": "Software Engineering",
    "faculty": "School of Computing",
    "primary_skill_level": "3"
  },
  "oguntimehindarasimi@gmail.com": {
    "full_name": "Oguntimehin Deborah Oluwakanyinsola",
    "gender": "Female",
    "whatsapp_number": "+2348146629073",
    "birthday": "2000-06-29",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Design & Management",
    "student_status": "Current Student",
    "matric_no": "25/2242",
    "department": "Software Engineering",
    "faculty": "School of Computing",
    "primary_skill_level": "1"
  },
  "nellyorion28@gmail.com": {
    "full_name": "Nelson Okere",
    "gender": "Male",
    "whatsapp_number": "+2347048172996",
    "birthday": "2000-08-11",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "24/1273",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "3"
  },
  "temitopeakanni017@gmail.com": {
    "full_name": "Akanni Temitope",
    "gender": "Female",
    "whatsapp_number": "+2348160889288",
    "birthday": "2000-08-02",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "25/1243",
    "department": "Nursing Science",
    "faculty": "Nursing Sciences",
    "primary_skill_level": "4"
  },
  "maryfavs12@gmail.com": {
    "full_name": "Okorie Chisomebi Mary Favour",
    "gender": "Female",
    "whatsapp_number": "+2349133247905",
    "birthday": "2000-04-24",
    "primary_track": "Data & AI",
    "secondary_track": "Infrastructure & Security",
    "student_status": "Current Student",
    "matric_no": "24/0704",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "2"
  },
  "enakirerhij8250@student.babcock.edu.ng": {
    "full_name": "Enakirerhi Julian Akpesiri",
    "gender": "Male",
    "whatsapp_number": "+2349034963339",
    "birthday": "2000-04-03",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Design & Management",
    "student_status": "Current Student",
    "matric_no": "23/1909",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "4"
  },
  "luxurywebcreativity@gmail.com": {
    "full_name": "Samuel Emmanuel",
    "gender": "Male",
    "whatsapp_number": "+2349123930234",
    "birthday": "2000-05-31",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "23/0263",
    "department": "Software Engineering",
    "faculty": "School of Computing",
    "primary_skill_level": "4"
  },
  "folushoogunlere@gmail.com": {
    "full_name": "Titobi",
    "gender": "Male",
    "whatsapp_number": "+2349066623468",
    "birthday": "2000-08-31",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "25/0054",
    "department": "Software Engineering",
    "faculty": "School of Computing",
    "primary_skill_level": "3"
  },
  "eleanyahenry54@gmail.com": {
    "full_name": "Eleanya Somtochukwu Henry",
    "gender": "Male",
    "whatsapp_number": "+2349095788035",
    "birthday": "2000-10-22",
    "primary_track": "Software Development & Engineering",
    "student_status": "Current Student",
    "matric_no": "23/2455",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "3"
  },
  "chibueze.k.muoneke@gmail.com": {
    "full_name": "Chibueze Muoneke",
    "gender": "Male",
    "whatsapp_number": "+2349156350191",
    "birthday": "2000-09-04",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Data & AI",
    "student_status": "Alumni"
  },
  "ronniiiip@gmail.com": {
    "full_name": "Egbu Princess Roni",
    "gender": "Female",
    "whatsapp_number": "+2349137489008",
    "birthday": "2000-07-19",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "23/0268",
    "department": "Software Engineering",
    "faculty": "School of Computing",
    "primary_skill_level": "4"
  },
  "treasure.alabo@gmail.com": {
    "full_name": "Treasure Alabo",
    "gender": "Female",
    "whatsapp_number": "+2349052480384",
    "birthday": "2000-03-20",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Design & Management",
    "student_status": "Current Student",
    "matric_no": "22/2858",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "3"
  },
  "ofavourite001@gmail.com": {
    "full_name": "Favour Oluwatunmibi",
    "gender": "Female",
    "whatsapp_number": "+2348169748438",
    "birthday": "2000-01-03",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "22/0215",
    "department": "Software Engineering",
    "faculty": "School of Computing",
    "primary_skill_level": "4"
  },
  "ojeifoemmanuella@gmail.com": {
    "full_name": "Isuduso Ojeifo",
    "gender": "Female",
    "whatsapp_number": "+2349067221893",
    "birthday": "2000-10-23",
    "primary_track": "Infrastructure & Security",
    "student_status": "Current Student",
    "matric_no": "22/2270",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "2"
  },
  "itunuoluwasogbesan@gmail.com": {
    "full_name": "Sogbesan Itunuoluwa Ayomi",
    "gender": "Female",
    "whatsapp_number": "+2347058702397",
    "birthday": "2000-01-01",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "22/0193",
    "department": "Software Engineering",
    "faculty": "School of Computing",
    "primary_skill_level": "1"
  },
  "chizobaijeoma02@gmail.com": {
    "full_name": "Chizoba Ijeoma Chinecherem",
    "gender": "Female",
    "whatsapp_number": "+2349011174641",
    "birthday": "2000-03-15",
    "primary_track": "Software Development & Engineering",
    "student_status": "Current Student",
    "matric_no": "22/1610",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "3"
  },
  "emenikechukwuka65@gmail.com": {
    "full_name": "Chukwuka Emenike",
    "gender": "Male",
    "whatsapp_number": "+2348167881530",
    "birthday": "2000-06-25",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "22/0469",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "4"
  },
  "olusanyataire@gmail.com": {
    "full_name": "Oghenetaire Olusanya",
    "gender": "Male",
    "whatsapp_number": "+2347058346049",
    "birthday": "2000-04-13",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Infrastructure & Security",
    "student_status": "Current Student",
    "matric_no": "22/2811",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "3"
  },
  "chidubeobinnacollins@gmail.com": {
    "full_name": "Obinna chidube",
    "gender": "Male",
    "whatsapp_number": "+2348124722620",
    "birthday": "2000-09-06",
    "primary_track": "Infrastructure & Security",
    "student_status": "Current Student",
    "matric_no": "22/1128",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "2"
  },
  "uwajedavid04@gmail.com": {
    "full_name": "David Uwaje Onyekachi",
    "gender": "Male",
    "whatsapp_number": "+2349079519750",
    "birthday": "2000-08-22",
    "primary_track": "Software Development & Engineering",
    "student_status": "Current Student",
    "matric_no": "22/0944",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "4"
  },
  "olugbejeb8351@student.babcock.edu.ng": {
    "full_name": "Boluwatife Modupe Olugbeje",
    "gender": "Male",
    "whatsapp_number": "+2347010051802",
    "birthday": "2000-05-23",
    "primary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "22/2408",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "2"
  },
  "batureemmanuel119@gmail.com": {
    "full_name": "Bature Ugo Emmanuel",
    "gender": "Male",
    "whatsapp_number": "+2347037790854",
    "birthday": "2000-05-05",
    "primary_track": "Infrastructure & Security",
    "student_status": "Current Student",
    "matric_no": "22/2063",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "3"
  },
  "ginaonuma5@gmail.com": {
    "full_name": "Georgina Onyeani Onumah",
    "gender": "Female",
    "whatsapp_number": "+2348077422422",
    "birthday": "2000-05-27",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Infrastructure & Security",
    "student_status": "Current Student",
    "matric_no": "22/0058",
    "department": "Software Engineering",
    "faculty": "School of Computing",
    "primary_skill_level": "2"
  },
  "ikemdavid8@gmail.com": {
    "full_name": "David Chukwudumebi Ikem",
    "gender": "Male",
    "whatsapp_number": "+2348100323180",
    "birthday": "2000-03-28",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "22/0232",
    "department": "Software Engineering",
    "faculty": "School of Computing",
    "primary_skill_level": "2"
  },
  "dannykode07@gmail.com": {
    "full_name": "Daniel Kadiri",
    "gender": "Male",
    "whatsapp_number": "+2348149800131",
    "birthday": "2000-10-07",
    "primary_track": "Design & Management",
    "student_status": "Current Student",
    "matric_no": "22/0003",
    "department": "Software Engineering",
    "faculty": "School of Computing",
    "primary_skill_level": "5"
  },
  "oluwafemiolatunji6002@gmail.com": {
    "full_name": "Oluwafemi Olatunji",
    "gender": "Male",
    "whatsapp_number": "+2349069627222",
    "birthday": "2000-02-27",
    "primary_track": "Software Development & Engineering",
    "student_status": "Current Student",
    "matric_no": "22/0566",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "5"
  },
  "dacodenzel@gmail.com": {
    "full_name": "Denzel Emmanuel-Daco",
    "gender": "Male",
    "whatsapp_number": "+2347067053953",
    "birthday": "2000-02-15",
    "primary_track": "Infrastructure & Security",
    "student_status": "Current Student",
    "matric_no": "23/0247",
    "department": "Software Engineering",
    "faculty": "School of Computing",
    "primary_skill_level": "3"
  },
  "obalabiadepoju9@gmail.com": {
    "full_name": "Obalabi Adepoju",
    "gender": "Male",
    "whatsapp_number": "+2349073287098",
    "birthday": "2000-11-14",
    "primary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "22/1273",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "4"
  },
  "smadagwa410@gmail.com": {
    "full_name": "Madagwa Success",
    "gender": "Female",
    "whatsapp_number": "+2349160869705",
    "birthday": "2000-03-13",
    "primary_track": "Design & Management",
    "student_status": "Current Student",
    "matric_no": "22/2386",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "4"
  },
  "awodelijah04@gmail.com": {
    "full_name": "Elijah Awodoyin",
    "gender": "Male",
    "whatsapp_number": "+234806190012@",
    "birthday": "2000-05-20",
    "primary_track": "Infrastructure & Security",
    "student_status": "Current Student",
    "matric_no": "22/2826",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "3"
  },
  "amarachiezealozie@gmail.com": {
    "full_name": "Eze-Alozie Amarachi",
    "gender": "Female",
    "whatsapp_number": "+2347045526681",
    "birthday": "2000-11-14",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Design & Management",
    "student_status": "Current Student",
    "matric_no": "22/0140",
    "department": "Software Engineering",
    "faculty": "School of Computing",
    "primary_skill_level": "3"
  },
  "dorcasokojie22@gmail.com": {
    "full_name": "Okojie-owahabanun dorcas osemudiamhen",
    "gender": "Female",
    "whatsapp_number": "+2348130797181",
    "birthday": "2000-05-10",
    "primary_track": "Design & Management",
    "student_status": "Current Student",
    "matric_no": "22/1300",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "1"
  },
  "savieeddie@gmail.com": {
    "full_name": "Saviour Bassey Edidiong",
    "gender": "Male",
    "whatsapp_number": "+2349067235713",
    "birthday": "2000-03-20",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Design & Management",
    "student_status": "Current Student",
    "matric_no": "23/2281",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "3"
  },
  "badejoolorunfunmi@gmail.com": {
    "full_name": "Badejo Olorunfunmi",
    "gender": "Male",
    "whatsapp_number": "+2348143086623",
    "birthday": "2000-04-07",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "23/2326",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "2"
  },
  "oluwatosin.sabiodun2006@gmail.com": {
    "full_name": "Abiodun Oluwatosin",
    "gender": "Male",
    "whatsapp_number": "+2349047491121",
    "birthday": "2000-04-12",
    "primary_track": "Software Development & Engineering",
    "student_status": "Current Student",
    "matric_no": "22/0605",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "3"
  },
  "tachoriel@gmail.com": {
    "full_name": "Okoye Maxwell Tagbo",
    "gender": "Male",
    "whatsapp_number": "+2347066995972",
    "birthday": "2000-03-31",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "22/0320",
    "department": "Software Engineering",
    "faculty": "School of Computing",
    "primary_skill_level": "2"
  },
  "moradeyosotunbo25@gmail.com": {
    "full_name": "Moradeyo Miriam SOTUNBO",
    "gender": "Female",
    "whatsapp_number": "+2348131698378",
    "birthday": "2000-07-25",
    "primary_track": "Data & AI",
    "secondary_track": "Design & Management",
    "student_status": "Current Student",
    "matric_no": "24/2687",
    "department": "History & International Studies",
    "faculty": "Education And Humanities",
    "primary_skill_level": "1"
  },
  "sagbekirstyn@gmail.com": {
    "full_name": "Kirstyn",
    "gender": "Female",
    "whatsapp_number": "+2347041412942",
    "birthday": "2000-09-29",
    "primary_track": "Design & Management",
    "student_status": "Current Student",
    "department": "Business Administration & Marketing",
    "faculty": "Management Sciences",
    "primary_skill_level": "1"
  },
  "tayoadefila08@gmail.com": {
    "full_name": "Adefila Olutayo Esther",
    "gender": "Female",
    "whatsapp_number": "+2348115602643",
    "birthday": "2000-06-25",
    "primary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "23/1285",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "3"
  },
  "yusufi5721@student.babcock.edu.ng": {
    "full_name": "Yusuf Ibrahim Ayomide",
    "gender": "Male",
    "whatsapp_number": "+2349123037497",
    "birthday": "2000-07-18",
    "primary_track": "Infrastructure & Security",
    "student_status": "Current Student",
    "matric_no": "22/1819",
    "department": "Software Engineering",
    "faculty": "School of Computing",
    "primary_skill_level": "4"
  },
  "michelle.kolawole13@gmail.com": {
    "full_name": "Michelle Kolawole",
    "gender": "Female",
    "whatsapp_number": "+2349036041280",
    "birthday": "2000-09-02",
    "primary_track": "Software Development & Engineering",
    "student_status": "Current Student",
    "matric_no": "23/1498",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "3"
  },
  "bumolaya@gmail.com": {
    "full_name": "Bukola Omokhafe Ajamolaya",
    "gender": "Female",
    "whatsapp_number": "+2348130347702",
    "birthday": "2000-05-27",
    "primary_track": "Software Development & Engineering",
    "student_status": "Current Student",
    "matric_no": "23/0441",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "3"
  },
  "jonnypez29@gmail.com": {
    "full_name": "Jonathan Akpan",
    "gender": "Male",
    "whatsapp_number": "+2349069016595",
    "birthday": "2000-10-29",
    "primary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "24/2598",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "2"
  },
  "dammysoji11@gmail.com": {
    "full_name": "Oluwadamilola Soji-Oderinde",
    "gender": "Male",
    "whatsapp_number": "+2347032065213",
    "birthday": "2000-11-09",
    "primary_track": "Software Development & Engineering",
    "student_status": "Current Student",
    "matric_no": "22/0092",
    "department": "Software Engineering",
    "faculty": "School of Computing",
    "primary_skill_level": "5"
  },
  "blessingdania7@gmail.com": {
    "full_name": "BLESSING DANIA",
    "gender": "Female",
    "whatsapp_number": "+2349063931205",
    "birthday": "2000-06-10",
    "primary_track": "Data & AI",
    "secondary_track": "Design & Management",
    "student_status": "Current Student",
    "matric_no": "22/0878",
    "department": "Public Health",
    "faculty": "Allied Health Sciences",
    "primary_skill_level": "1"
  },
  "oluwabusayoawofadeju@gmail.com": {
    "full_name": "Awofadeju oluwabusayo Kehinde",
    "gender": "Male",
    "whatsapp_number": "+2347038738141",
    "birthday": "2000-12-12",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Design & Management",
    "student_status": "Current Student",
    "matric_no": "23/1257",
    "department": "Computer Engineering",
    "faculty": "Engineering",
    "primary_skill_level": "1"
  },
  "belovedafolabi31@gmail.com": {
    "full_name": "Afolabi Beloved Joseph",
    "gender": "Male",
    "whatsapp_number": "+2348081993024",
    "birthday": "2000-12-30",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Design & Management",
    "student_status": "Current Student",
    "matric_no": "23/1102",
    "department": "Computer Engineering",
    "faculty": "Engineering",
    "primary_skill_level": "1"
  },
  "nielroe63@gmail.com": {
    "full_name": "Okodugha Daniel",
    "gender": "Male",
    "whatsapp_number": "+2349169773052",
    "birthday": "2000-02-14",
    "primary_track": "Data & AI",
    "secondary_track": "Design & Management",
    "student_status": "Current Student",
    "matric_no": "23/2467",
    "department": "Accounting",
    "faculty": "Management Sciences",
    "primary_skill_level": "1"
  },
  "okerekeozichi86@gmail.com": {
    "full_name": "Okereke Ozichi",
    "gender": "Female",
    "whatsapp_number": "+2348057419828",
    "birthday": "2000-11-28",
    "primary_track": "Data & AI",
    "secondary_track": "Design & Management",
    "student_status": "Current Student",
    "matric_no": "24/1315",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "1"
  },
  "devinolugbore@gmail.com": {
    "full_name": "Olugbore Devin Olamikun",
    "gender": "Male",
    "whatsapp_number": "+2348132790700",
    "birthday": "2000-04-26",
    "primary_track": "Software Development & Engineering",
    "student_status": "Current Student",
    "matric_no": "24/1567",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "2"
  },
  "fadarea0255@student.babcock.edu.ng": {
    "full_name": "Ajibola Fadare",
    "gender": "Female",
    "whatsapp_number": "+2347049518619",
    "birthday": "2000-01-07",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Design & Management",
    "student_status": "Current Student",
    "matric_no": "24/0152",
    "department": "Software Engineering",
    "faculty": "School of Computing",
    "primary_skill_level": "2"
  },
  "ppennyziri@gmail.com": {
    "full_name": "Peniel Chikeziri Nwaneri",
    "gender": "Male",
    "whatsapp_number": "+2348159601723",
    "birthday": "2000-09-05",
    "primary_track": "Software Development & Engineering",
    "student_status": "Current Student",
    "matric_no": "24/0404",
    "department": "Software Engineering",
    "faculty": "School of Computing",
    "primary_skill_level": "2"
  },
  "mypersonality12@gmail.com": {
    "full_name": "Temini Adedipe",
    "gender": "Male",
    "whatsapp_number": "+2348145709655",
    "birthday": "2000-06-16",
    "primary_track": "Software Development & Engineering",
    "student_status": "Current Student",
    "matric_no": "24/0140",
    "department": "Software Engineering",
    "faculty": "School of Computing",
    "primary_skill_level": "1"
  },
  "aweleoluonye@gmail.com": {
    "full_name": "Awele Oluonye",
    "gender": "Male",
    "whatsapp_number": "+2349070613315",
    "birthday": "2000-05-10",
    "primary_track": "Data & AI",
    "secondary_track": "Design & Management",
    "student_status": "Current Student",
    "matric_no": "23/0749",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "4"
  },
  "michaelosnjoku@gmail.com": {
    "full_name": "Michael Njoku",
    "gender": "Male",
    "whatsapp_number": "+2348170314455",
    "birthday": "2000-01-07",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "24/0366",
    "department": "Software Engineering",
    "faculty": "School of Computing",
    "primary_skill_level": "2"
  },
  "alliuvictor@gmail.com": {
    "full_name": "Alliu Victor",
    "gender": "Male",
    "whatsapp_number": "+2347070222845",
    "birthday": "2000-03-17",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Infrastructure & Security",
    "student_status": "Current Student",
    "matric_no": "22/0960",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "3"
  },
  "oje.omojola@gmail.com": {
    "full_name": "Omojola Ojehonmon",
    "gender": "Male",
    "whatsapp_number": "+2348131937374",
    "birthday": "2000-01-10",
    "primary_track": "Data & AI",
    "secondary_track": "Design & Management",
    "student_status": "Current Student",
    "matric_no": "23/2634",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "3"
  },
  "tundeolusodo@gmail.com": {
    "full_name": "Ayotunde Olusodo",
    "gender": "Male",
    "whatsapp_number": "+2348123404603",
    "birthday": "2000-07-11",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "23/2325",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "2"
  },
  "dannysdomainoriginal@gmail.com": {
    "full_name": "Charles Daniel Chinedum",
    "gender": "Male",
    "whatsapp_number": "+2348141289623",
    "birthday": "2000-03-06",
    "primary_track": "Software Development & Engineering",
    "student_status": "Current Student",
    "matric_no": "24/1960",
    "department": "Software Engineering",
    "faculty": "School of Computing",
    "primary_skill_level": "4"
  },
  "eddyfy23@gmail.com": {
    "full_name": "Olaoluwakitan Oretade",
    "gender": "Male",
    "whatsapp_number": "+2347017578829",
    "birthday": "2000-03-05",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "23/2041",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "3"
  },
  "cossyanne@gmail.com": {
    "full_name": "Anuebunwa Cosisochukwu",
    "gender": "Female",
    "whatsapp_number": "+2348174466338",
    "birthday": "2000-03-16",
    "primary_track": "Design & Management",
    "student_status": "Current Student",
    "matric_no": "22/0564",
    "department": "Human Nutrition and Dietetics",
    "faculty": "Allied Health Sciences",
    "primary_skill_level": "3"
  },
  "abolajioduneye9@gmail.com": {
    "full_name": "Abolaji Oduneye Daniel",
    "gender": "Male",
    "whatsapp_number": "+2348130737059",
    "birthday": "2000-10-27",
    "primary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "23/1087",
    "department": "Accounting",
    "faculty": "Management Sciences",
    "primary_skill_level": "1"
  },
  "kwindeola@gmail.com": {
    "full_name": "Taslim Kanyinsola Adeola",
    "gender": "Female",
    "whatsapp_number": "+2347051860930",
    "birthday": "2000-05-08",
    "primary_track": "Data & AI",
    "secondary_track": "Infrastructure & Security",
    "student_status": "Current Student",
    "matric_no": "22/1963",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "2"
  },
  "zubbyobunadike@gmail.com": {
    "full_name": "Nzubechukwu Obunadike",
    "gender": "Male",
    "whatsapp_number": "+2349155937007",
    "birthday": "2000-08-11",
    "primary_track": "Infrastructure & Security",
    "secondary_track": "Design & Management",
    "student_status": "Current Student",
    "matric_no": "23/2932",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "3"
  },
  "iseoluwaojo2@gmail.com": {
    "full_name": "Ojo Iseoluwa Miracle",
    "gender": "Female",
    "whatsapp_number": "+2348109017359",
    "birthday": "2000-03-03",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "24/2317",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "2"
  },
  "ameenat.mj.10@gmail.com": {
    "full_name": "Ameenat Mofeoluwa Okeowo",
    "gender": "Female",
    "whatsapp_number": "+2348116997469",
    "birthday": "2000-07-10",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "23/0121",
    "department": "Software Engineering",
    "faculty": "School of Computing",
    "primary_skill_level": "2"
  },
  "aladeoyinlolami17@gmail.com": {
    "full_name": "Oyinlolami Eunice Alade",
    "gender": "Female",
    "whatsapp_number": "+2348073340175",
    "birthday": "2000-01-17",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "23/2315",
    "department": "Economics",
    "faculty": "Veronica Adeleke School of Social Sciences",
    "primary_skill_level": "1"
  },
  "toluwaniyiolagunju@gmail.com": {
    "full_name": "Emmanuel Toluwaniyi Olagunju",
    "gender": "Male",
    "whatsapp_number": "+2348141531681",
    "birthday": "2000-03-26",
    "primary_track": "Data & AI",
    "secondary_track": "Design & Management",
    "student_status": "Current Student",
    "matric_no": "25/0498",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "2"
  },
  "wasilatadegbite00@gmail.com": {
    "full_name": "Adegbite Hameed Olamilekan",
    "gender": "Male",
    "whatsapp_number": "+2347081586224",
    "birthday": "2000-07-06",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Infrastructure & Security",
    "student_status": "Current Student",
    "matric_no": "25/0977",
    "department": "Information Technology",
    "faculty": "School of Computing",
    "primary_skill_level": "1"
  },
  "imisioluwaaderibigbe13@gmail.com": {
    "full_name": "Aderibigbe Imisioluwa Temilayo",
    "gender": "Male",
    "whatsapp_number": "+2348187239522",
    "birthday": "2000-04-13",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Data & AI",
    "student_status": "Alumni"
  },
  "liromenu@gmail.com": {
    "full_name": "Leroy Kemka Iromenu",
    "gender": "Male",
    "whatsapp_number": "+2348146885802",
    "birthday": "2000-05-21",
    "primary_track": "Software Development & Engineering",
    "student_status": "Current Student",
    "matric_no": "25/0149",
    "department": "Software Engineering",
    "faculty": "School of Computing",
    "primary_skill_level": "2"
  },
  "ifeanyiogbuanu5@gmail.com": {
    "full_name": "Ifeanyi ogbuanu",
    "gender": "Male",
    "whatsapp_number": "+2347030101509",
    "birthday": "2000-01-28",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "25/0497",
    "department": "Software Engineering",
    "faculty": "School of Computing",
    "primary_skill_level": "1"
  },
  "keshinroo2974@student.babcock.edu.ng": {
    "full_name": "Keshinro oluwanifemi Emmanuella",
    "gender": "Female",
    "whatsapp_number": "+2349034611239",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "22/0074",
    "department": "Software Engineering",
    "faculty": "School of Computing",
    "primary_skill_level": "1"
  },
  "horlarbordeyjohn23@gmail.com": {
    "full_name": "John Olabode",
    "gender": "Male",
    "whatsapp_number": "+2348161427810",
    "birthday": "2000-04-15",
    "primary_track": "Data & AI",
    "secondary_track": "Design & Management",
    "student_status": "Current Student",
    "matric_no": "ComO026",
    "department": "Computer Science and Information Systems",
    "faculty": "School of Computing",
    "primary_skill_level": "2"
  },
  "providentialprov1@gmail.com": {
    "full_name": "Providence Oduok",
    "gender": "Female",
    "whatsapp_number": "+2348128420633",
    "birthday": "2000-07-24",
    "primary_track": "Data & AI",
    "secondary_track": "Infrastructure & Security",
    "student_status": "Current Student",
    "matric_no": "23/2143",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "3"
  },
  "olabodealao585@gmail.com": {
    "full_name": "Olabode Abdul-Majeed Alao",
    "gender": "Male",
    "whatsapp_number": "+2347040724260",
    "birthday": "2000-05-08",
    "primary_track": "Data & AI",
    "secondary_track": "Infrastructure & Security",
    "student_status": "Current Student",
    "matric_no": "22/2384",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "3"
  },
  "odukaleo4715@student.babcock.edu.ng": {
    "full_name": "Oluwatobiloba Odukale",
    "gender": "Male",
    "whatsapp_number": "+2347038596007",
    "birthday": "2000-12-15",
    "primary_track": "Design & Management",
    "student_status": "Current Student",
    "matric_no": "23/0775",
    "department": "Business Administration and Marketing",
    "faculty": "Management Sciences",
    "primary_skill_level": "3"
  },
  "dukeakwuobu06@gmail.com": {
    "full_name": "Duke Simeon-Akwuobu",
    "gender": "Male",
    "whatsapp_number": "+2348063789633",
    "birthday": "2000-07-06",
    "primary_track": "Design & Management",
    "student_status": "Current Student",
    "matric_no": "23/0260",
    "department": "Software Engineering",
    "faculty": "School of Computing",
    "primary_skill_level": "1"
  },
  "okuneyehelen@gmail.com": {
    "full_name": "Helen Ademifiyinfoluwa Okuneye",
    "gender": "Female",
    "whatsapp_number": "+2347061723588",
    "birthday": "2000-10-10",
    "primary_track": "Data & AI",
    "secondary_track": "Design & Management",
    "student_status": "Current Student",
    "matric_no": "24/2112",
    "department": "Information Technology",
    "faculty": "School of Computing",
    "primary_skill_level": "1"
  },
  "okesonfavour8@gmail.com": {
    "full_name": "Okeson Favour Chidinma",
    "gender": "Female",
    "whatsapp_number": "+2349128872243",
    "birthday": "2000-01-01",
    "primary_track": "Software Development & Engineering",
    "student_status": "Current Student",
    "matric_no": "25/2593",
    "department": "Software Engineering",
    "faculty": "School of Computing",
    "primary_skill_level": "3"
  },
  "vincentoluwasuyi223@gmail.com": {
    "full_name": "Vincent Oluwasuyi",
    "gender": "Male",
    "whatsapp_number": "+2349057212612",
    "birthday": "2000-08-22",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "25/0069",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "1"
  },
  "n1f3xx@gmail.com": {
    "full_name": "Oluwanifemi Ogunkomaya Ayotomiwa",
    "gender": "Male",
    "whatsapp_number": "+2348147254632",
    "birthday": "2000-01-15",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "25/0186",
    "department": "Software Engineering",
    "faculty": "School of Computing",
    "primary_skill_level": "1"
  },
  "akinolaoloyedefatai@gmail.com": {
    "full_name": "Akinola-Oloyede",
    "gender": "Male",
    "whatsapp_number": "+2347032360542",
    "birthday": "2000-07-18",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Design & Management",
    "student_status": "Current Student",
    "matric_no": "25/0332",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "1"
  },
  "omekadivine1@gmail.com": {
    "full_name": "Divine Omeka",
    "gender": "Male",
    "whatsapp_number": "+2347026989293",
    "birthday": "2000-11-08",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "25/2322",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "1"
  },
  "michealudekwu@gmail.com": {
    "full_name": "Udekwu Chinedu Micheal",
    "gender": "Male",
    "whatsapp_number": "+2349071478034",
    "birthday": "2000-11-11",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "23/0764",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "4"
  },
  "uzochukwu.favour310@gmail.com": {
    "full_name": "Favour Adachukwu Uzochukwu",
    "gender": "Female",
    "whatsapp_number": "+2348055808058",
    "birthday": "2000-11-03",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "23/0669",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "3"
  },
  "chidubemiwuh@gmail.com": {
    "full_name": "Chidubem Iwuh",
    "gender": "Male",
    "whatsapp_number": "+2348120787401",
    "birthday": "2000-04-13",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "22/0289",
    "department": "Software Engineering",
    "faculty": "School of Computing",
    "primary_skill_level": "2"
  },
  "dollarajibulu@gmail.com": {
    "full_name": "Dolapo Felix olarinde",
    "gender": "Male",
    "whatsapp_number": "+2348053998900",
    "birthday": "2000-07-21",
    "primary_track": "Software Development & Engineering",
    "student_status": "Current Student",
    "matric_no": "23/1448",
    "department": "Civil Engineering",
    "faculty": "Engineering",
    "primary_skill_level": "2"
  },
  "okojieab21@gmail.com": {
    "full_name": "Abraham Okokie",
    "gender": "Male",
    "whatsapp_number": "+2349155278720",
    "birthday": "2000-07-21",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Infrastructure & Security",
    "student_status": "Current Student",
    "matric_no": "23/0181",
    "department": "Software Engineering",
    "faculty": "School of Computing",
    "primary_skill_level": "2"
  },
  "tomisola2008@gmail.com": {
    "full_name": "Adeyemi Oluwatomi",
    "gender": "Female",
    "whatsapp_number": "+2347049961525",
    "birthday": "2000-03-14",
    "primary_track": "Software Development & Engineering",
    "student_status": "Current Student",
    "matric_no": "23/0006",
    "department": "Software Engineering",
    "faculty": "School of Computing",
    "primary_skill_level": "3"
  },
  "destiny.chidera0812@gmail.com": {
    "full_name": "Chidera Jude-Onwusonye Destiny",
    "gender": "Female",
    "whatsapp_number": "+2349048232005",
    "birthday": "2000-12-16",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "25/2156",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "1"
  },
  "lamicrypt.001@gmail.com": {
    "full_name": "Adeniyi Olamide Esther",
    "gender": "Female",
    "whatsapp_number": "+2349032186786",
    "birthday": "2000-01-02",
    "primary_track": "Design & Management",
    "student_status": "Current Student",
    "matric_no": "23/1764",
    "department": "Computer Science",
    "faculty": "Science And Technology",
    "primary_skill_level": "3"
  },
  "faithogundimu78@gmail.com": {
    "full_name": "Ogundimu Faith Morenikeji",
    "gender": "Female",
    "whatsapp_number": "+2348131836772",
    "birthday": "2000-04-28",
    "primary_track": "Design & Management",
    "student_status": "Current Student",
    "matric_no": "22/1540",
    "department": "Mass Communication",
    "faculty": "Veronica Adeleke School of Social Sciences",
    "primary_skill_level": "1"
  },
  "ayenishn@gmail.com": {
    "full_name": "Ayeni Oluwashinaayomi",
    "gender": "Male",
    "whatsapp_number": "+2348061672156",
    "birthday": "2000-09-02",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "23/2990",
    "department": "Medical Laboratory Science",
    "faculty": "Allied Health Sciences",
    "primary_skill_level": "1"
  },
  "ntmark2004@gmail.com": {
    "full_name": "Mark Ndubuisi",
    "gender": "Male",
    "whatsapp_number": "+2348116087743",
    "birthday": "2000-08-28",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "2022/244236",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "4"
  },
  "oyebajoolamide49@gmail.com": {
    "full_name": "Olamide Oyebajo",
    "gender": "Male",
    "whatsapp_number": "+2349122325945",
    "birthday": "2000-05-30",
    "primary_track": "Infrastructure & Security",
    "student_status": "Current Student",
    "matric_no": "25/1274",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "1"
  },
  "tobisadik312@gmail.com": {
    "full_name": "Oluwatobiloba bakare",
    "gender": "Male",
    "whatsapp_number": "+2348127046360",
    "birthday": "2000-12-01",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "25/0769",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "1"
  },
  "chiomankenchor81@gmail.com": {
    "full_name": "NKENCHOR CHIOMA MEDLINE",
    "gender": "Female",
    "whatsapp_number": "+2348115300443",
    "birthday": "2000-06-13",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "22/2403",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "2"
  },
  "fasipeabigael01@gmail.com": {
    "full_name": "FASIPE ABIGAEL DAMILOLA",
    "gender": "Female",
    "whatsapp_number": "+2349077268654",
    "birthday": "2000-10-24",
    "primary_track": "Software Development & Engineering",
    "student_status": "Current Student"
  },
  "oreoluwashittu21@gmail.com": {
    "full_name": "Oreoluwa Senami Shittu",
    "gender": "Female",
    "whatsapp_number": "+2349039705988",
    "birthday": "2000-12-04",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "25/0330",
    "department": "Software Engineering",
    "faculty": "School of Computing",
    "primary_skill_level": "1"
  },
  "kamdirichukwuwosuezi@gmail.com": {
    "full_name": "Kamdirichukwu Blossom Wosu-Ezi",
    "gender": "Female",
    "whatsapp_number": "+2348166442424",
    "birthday": "2000-03-22",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "25/1313",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "4"
  },
  "addisonhackss14@gmail.com": {
    "full_name": "Boluwatife Adeyemi",
    "gender": "Female",
    "whatsapp_number": "+2348165400068",
    "birthday": "2000-05-02",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Infrastructure & Security",
    "student_status": "Current Student",
    "matric_no": "23/0041",
    "department": "Software Engineering",
    "faculty": "School of Computing",
    "primary_skill_level": "2"
  },
  "charlesbenson692@gmail.com": {
    "full_name": "Charles Benson Kelechukwu",
    "gender": "Male",
    "whatsapp_number": "+2347062753420",
    "birthday": "2000-11-22",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "23/2710",
    "department": "Information Technology",
    "faculty": "School of Computing",
    "primary_skill_level": "2"
  },
  "ebaho4805@student.babcock.edu.ng": {
    "full_name": "EBAH OGHENEOGAGA",
    "gender": "Male",
    "whatsapp_number": "+2349163960616",
    "birthday": "2000-12-29",
    "primary_track": "Infrastructure & Security",
    "student_status": "Current Student",
    "matric_no": "23/0813",
    "department": "Information Technology",
    "faculty": "School of Computing",
    "primary_skill_level": "2"
  },
  "danielalabi2024@gmail.com": {
    "full_name": "Daniel Osinemega Alabi",
    "gender": "Male",
    "whatsapp_number": "+2349167662215",
    "birthday": "2000-10-03",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "25/0266",
    "department": "Software Engineering",
    "faculty": "School of Computing",
    "primary_skill_level": "1"
  },
  "adebayok4373@student.babcock.edu.ng": {
    "full_name": "Adebayo Kehinde Abraham",
    "gender": "Male",
    "whatsapp_number": "+2348135057905",
    "birthday": "2000-02-18",
    "primary_track": "Software Development & Engineering",
    "student_status": "Current Student",
    "matric_no": "24/1866",
    "department": "Software Engineering",
    "faculty": "School of Computing",
    "primary_skill_level": "2"
  },
  "samuelojo890@gmail.com": {
    "full_name": "OJO TITOBIOLUWA SAMUEL",
    "gender": "Male",
    "whatsapp_number": "+2348061988019",
    "birthday": "2000-06-26",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Design & Management",
    "student_status": "Current Student",
    "matric_no": "23/2759",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "3"
  },
  "olupelumioshundiya@gmail.com": {
    "full_name": "Oshundiya Oluwapelumi",
    "gender": "Male",
    "whatsapp_number": "+2349164352540",
    "birthday": "2000-08-29",
    "primary_track": "Data & AI",
    "secondary_track": "Infrastructure & Security",
    "student_status": "Current Student",
    "matric_no": "19/2255",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "5"
  },
  "ezebekeedavid@gmail.com": {
    "full_name": "Eze-Bekee David",
    "gender": "Male",
    "whatsapp_number": "+2349150778462",
    "birthday": "2000-01-25",
    "primary_track": "Infrastructure & Security",
    "student_status": "Current Student",
    "matric_no": "22/0088",
    "department": "Software Engineering",
    "faculty": "School of Computing",
    "primary_skill_level": "3"
  },
  "emogoghena@gmail.com": {
    "full_name": "Femi-Olagundoye OluwaFeranmi OluwaDarasimi",
    "gender": "Female",
    "whatsapp_number": "+2349153849696",
    "birthday": "2000-06-24",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "22/0147",
    "department": "Software Engineering",
    "faculty": "School of Computing",
    "primary_skill_level": "4"
  },
  "emuekharekingdavid@gmail.com": {
    "full_name": "King-David Emuekhare",
    "gender": "Male",
    "whatsapp_number": "+2349160196189",
    "birthday": "2000-06-11",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Design & Management",
    "student_status": "Current Student",
    "matric_no": "23/1122",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "3"
  },
  "olunubigreatness@gmail.com": {
    "full_name": "Olunubi Greatness Obama",
    "gender": "Male",
    "whatsapp_number": "+2349138882669",
    "birthday": "2000-11-18",
    "primary_track": "Data & AI",
    "secondary_track": "Infrastructure & Security",
    "student_status": "Current Student",
    "matric_no": "25/2044",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "3"
  },
  "dcchris006@gmail.com": {
    "full_name": "Dorachima Onwusah",
    "gender": "Female",
    "whatsapp_number": "+2347010253812",
    "birthday": "2000-09-15",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Design & Management",
    "student_status": "Current Student",
    "matric_no": "23/0984",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "1"
  },
  "kachiobata@gmail.com": {
    "full_name": "Onyelukachukwu Obata",
    "gender": "Male",
    "whatsapp_number": "+2348092226795",
    "birthday": "2000-04-22",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Design & Management",
    "student_status": "Current Student",
    "matric_no": "24/0443",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "3"
  },
  "enebeligreat53@gmail.com": {
    "full_name": "Enebeli great nonso",
    "gender": "Male",
    "whatsapp_number": "+2347057583770",
    "birthday": "2000-01-28",
    "primary_track": "Software Development & Engineering",
    "student_status": "Current Student",
    "matric_no": "25/2724",
    "department": "Software Engineering",
    "faculty": "School of Computing",
    "primary_skill_level": "3"
  },
  "dan.doyin@gmail.com": {
    "full_name": "Daniel Fagbohunlu",
    "gender": "Male",
    "whatsapp_number": "+2349156533118",
    "birthday": "2000-08-23",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Infrastructure & Security",
    "student_status": "Current Student",
    "matric_no": "23/2388",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "3"
  },
  "praisei4107@student.babcock.edu.ng": {
    "full_name": "Praise Israel Chikwuraa",
    "gender": "Male",
    "whatsapp_number": "+2349032107449",
    "birthday": "2000-10-05",
    "primary_track": "Infrastructure & Security",
    "student_status": "Current Student",
    "matric_no": "22/0123",
    "department": "Software Engineering",
    "faculty": "Engineering",
    "primary_skill_level": "3"
  },
  "stephenekeng15@gmail.com": {
    "full_name": "Stephen Ekeng",
    "gender": "Male",
    "whatsapp_number": "+2347049865513",
    "birthday": "2000-05-03",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "24/1092",
    "department": "Software Engineering",
    "faculty": "School of Computing",
    "primary_skill_level": "2"
  },
  "princehosanna45@gmail.com": {
    "full_name": "Ijeoma Hosanna",
    "gender": "Male",
    "whatsapp_number": "+2347069578592",
    "birthday": "2000-04-19",
    "primary_track": "Design & Management",
    "student_status": "Current Student",
    "matric_no": "22/1231",
    "department": "Information Resources Management",
    "faculty": "Management Sciences",
    "primary_skill_level": "1"
  },
  "seyiadurota@gmail.com": {
    "full_name": "Adurota Oluwaseyi Anthony",
    "gender": "Male",
    "whatsapp_number": "+2349162430290",
    "birthday": "2000-05-19",
    "primary_track": "Software Development & Engineering",
    "secondary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "25/0390",
    "department": "Mass Communication",
    "faculty": "Veronica Adeleke School of Social Sciences",
    "primary_skill_level": "1"
  },
  "aseztreasure@gmail.com": {
    "full_name": "Aiyegbusi Eniola Joseph",
    "gender": "Male",
    "whatsapp_number": "+2349165993239",
    "birthday": "2000-08-05",
    "primary_track": "Data & AI",
    "student_status": "Current Student",
    "matric_no": "25/2488",
    "department": "Information Technology",
    "faculty": "School of Computing",
    "primary_skill_level": "1"
  },
  "bamsondavid1@gmail.com": {
    "full_name": "David Bamson Eyitomilayo",
    "gender": "Male",
    "whatsapp_number": "+2348149380104",
    "birthday": "2000-03-28",
    "primary_track": "Software Development & Engineering",
    "student_status": "Current Student",
    "matric_no": "23/2732",
    "department": "Computer Science",
    "faculty": "School of Computing",
    "primary_skill_level": "2"
  }
};

/** Check if an email has seed data available */
export function getMemberSeedData(email: string): MemberSeedProfile | null {
  return MEMBER_SEED_DATA[email.toLowerCase().trim()] ?? null;
}
